// Copyright (C) 2019-2026 Provable Inc.
// This file is part of the Leo library.

// The Leo library is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// The Leo library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with the Leo library. If not, see <https://www.gnu.org/licenses/>.

//! Builds the symbol strings into `Symbol` values.

use std::{
    error::Error,
    env, fs,
    fmt,
    io::{BufWriter, Read, Write},
    path::{Path, PathBuf},
    process::ExitCode,
};

const PRE_DEFINED_HEADER: &str = "// @generated by build.rs. Do not edit.\nconst PRE_DEFINED: &[&str] = &[\n";
const SYM_HEADER: &str = "];\n\n#[allow(non_upper_case_globals)]\npub mod sym {\n";
const SYM_FOOTER: &str = "}\n";

struct SymbolLine<'a> {
    ident: &'a str,
    literal: Option<&'a str>,
}

#[derive(Debug)]
enum BuildError {
    MissingEnvVar(&'static str, env::VarError),
    Io { action: &'static str, path: PathBuf, source: std::io::Error },
    InvalidSymbolEntry { path: PathBuf, line_no: usize },
    InvalidStringLiteral { ident: String, path: PathBuf, line_no: usize },
    InvalidIdentifier { ident: String, path: PathBuf, line_no: usize },
    NoSymbolsFound { path: PathBuf },
}

impl fmt::Display for BuildError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingEnvVar(name, source) => write!(f, "missing environment variable {name}: {source}"),
            Self::Io { action, path, source } => write!(f, "failed to {action} {}: {source}", path.display()),
            Self::InvalidSymbolEntry { path, line_no } => {
                write!(f, "invalid symbol entry at {}:{line_no}", path.display())
            }
            Self::InvalidStringLiteral { ident, path, line_no } => {
                write!(f, "expected string literal for symbol {ident} at {}:{line_no}", path.display())
            }
            Self::InvalidIdentifier { ident, path, line_no } => {
                write!(f, "invalid symbol identifier '{ident}' at {}:{line_no}", path.display())
            }
            Self::NoSymbolsFound { path } => write!(f, "no symbols found in {}", path.display()),
        }
    }
}

impl Error for BuildError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::MissingEnvVar(_, source) => Some(source),
            Self::Io { source, .. } => Some(source),
            Self::InvalidSymbolEntry { .. }
            | Self::InvalidStringLiteral { .. }
            | Self::InvalidIdentifier { .. }
            | Self::NoSymbolsFound { .. } => None,
        }
    }
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("cargo:warning={err}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), BuildError> {
    let manifest_dir = manifest_dir()?;
    let input_path = manifest_dir.join("symbols.txt");
    println!("cargo:rerun-if-changed={}", input_path.display());

    let input = read_symbols(&input_path)?;
    let symbols = parse_symbols(&input, &input_path)?;
    if symbols.is_empty() {
        return Err(BuildError::NoSymbolsFound { path: input_path });
    }

    let out_dir = out_dir()?;
    let out_path = out_dir.join("symbols_generated.rs");
    let output = fs::File::create(&out_path).map_err(|source| BuildError::Io {
        action: "write",
        path: out_path.clone(),
        source,
    })?;
    let mut output = BufWriter::new(output);

    write_output(&mut output, PRE_DEFINED_HEADER, &out_path)?;
    emit_pre_defined(&symbols, &mut output, &out_path)?;

    write_output(&mut output, SYM_HEADER, &out_path)?;
    emit_sym_module(&symbols, &mut output, &out_path)?;

    write_output(&mut output, SYM_FOOTER, &out_path)?;
    output.flush().map_err(|source| BuildError::Io { action: "write", path: out_path, source })?;
    Ok(())
}

fn manifest_dir() -> Result<PathBuf, BuildError> {
    env::var("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .map_err(|source| BuildError::MissingEnvVar("CARGO_MANIFEST_DIR", source))
}

fn out_dir() -> Result<PathBuf, BuildError> {
    env::var("OUT_DIR")
        .map(PathBuf::from)
        .map_err(|source| BuildError::MissingEnvVar("OUT_DIR", source))
}

fn read_symbols(path: &Path) -> Result<String, BuildError> {
    let input_len = fs::metadata(path).map(|meta| meta.len() as usize).unwrap_or(0);
    let mut input = String::with_capacity(input_len);
    let mut file = fs::File::open(path).map_err(|source| BuildError::Io {
        action: "read",
        path: path.to_path_buf(),
        source,
    })?;
    file.read_to_string(&mut input).map_err(|source| BuildError::Io {
        action: "read",
        path: path.to_path_buf(),
        source,
    })?;
    Ok(input)
}

fn is_valid_ident(ident: &str) -> bool {
    let mut chars = ident.chars();
    if let Some(first) = chars.next() {
        (first == '_' || first.is_ascii_alphabetic()) && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
    } else {
        false
    }
}

fn parse_symbol_line<'a>(line: &'a str, path: &Path, line_no: usize) -> Result<Option<SymbolLine<'a>>, BuildError> {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with("//") {
        return Ok(None);
    }

    let (ident, literal) = match trimmed.split_once(':') {
        Some((left, right)) => {
            let ident = left.trim();
            let literal = right.trim();
            if ident.is_empty() || literal.is_empty() {
                return Err(BuildError::InvalidSymbolEntry { path: path.to_path_buf(), line_no });
            }
            if !(literal.starts_with('"') && literal.ends_with('"')) {
                return Err(BuildError::InvalidStringLiteral {
                    ident: ident.to_owned(),
                    path: path.to_path_buf(),
                    line_no,
                });
            }
            (ident, Some(literal))
        }
        None => (trimmed, None),
    };

    if !is_valid_ident(ident) {
        return Err(BuildError::InvalidIdentifier {
            ident: ident.to_owned(),
            path: path.to_path_buf(),
            line_no,
        });
    }

    Ok(Some(SymbolLine { ident, literal }))
}

fn parse_symbols<'a>(input: &'a str, path: &Path) -> Result<Vec<SymbolLine<'a>>, BuildError> {
    let mut symbols = Vec::with_capacity(input.lines().count());
    for (line_no, line) in input.lines().enumerate() {
        let Some(symbol) = parse_symbol_line(line, path, line_no + 1)? else {
            continue;
        };

        symbols.push(symbol);
    }

    Ok(symbols)
}

fn write_output(output: &mut impl Write, contents: &str, out_path: &Path) -> Result<(), BuildError> {
    output.write_all(contents.as_bytes()).map_err(|source| BuildError::Io {
        action: "write",
        path: out_path.to_path_buf(),
        source,
    })
}

fn write_output_fmt(output: &mut impl Write, out_path: &Path, args: fmt::Arguments<'_>) -> Result<(), BuildError> {
    output.write_fmt(args).map_err(|source| BuildError::Io {
        action: "write",
        path: out_path.to_path_buf(),
        source,
    })
}

fn emit_pre_defined(symbols: &[SymbolLine<'_>], output: &mut impl Write, out_path: &Path) -> Result<(), BuildError> {
    for symbol in symbols {
        match symbol.literal {
            Some(literal) => write_output_fmt(output, out_path, format_args!("    {literal},\n"))?,
            None => write_output_fmt(output, out_path, format_args!("    {:?},\n", symbol.ident))?,
        }
    }

    Ok(())
}

fn emit_sym_module(symbols: &[SymbolLine<'_>], output: &mut impl Write, out_path: &Path) -> Result<(), BuildError> {
    for (index, symbol) in symbols.iter().enumerate() {
        write_output_fmt(
            output,
            out_path,
            format_args!(
                "    pub const {}: crate::symbol::Symbol = crate::symbol::Symbol::new({index});\n",
                symbol.ident
            ),
        )?;
    }

    Ok(())
}
