use std::{
    env,
    fs,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing"));
    let input_path = manifest_dir.join("symbols.txt");
    println!("cargo:rerun-if-changed={}", input_path.display());

    let input = fs::read_to_string(&input_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", input_path.display()));
    let symbols = parse_symbols(&input, &input_path);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let out_path = out_dir.join("symbols_generated.rs");

    let mut output = String::with_capacity(symbols.len() * 64 + 256);
    output.push_str("// @generated by build.rs. Do not edit.\n");
    output.push_str("const PRE_DEFINED: &[&str] = &[\n");
    for symbol in &symbols {
        match &symbol.string_literal {
            Some(literal) => {
                output.push_str("    ");
                output.push_str(literal);
                output.push_str(",\n");
            }
            None => {
                output.push_str("    \"");
                output.push_str(&symbol.ident);
                output.push_str("\",\n");
            }
        }
    }
    output.push_str("];\n\n");
    output.push_str("pub mod sym {\n");
    for (index, symbol) in symbols.iter().enumerate() {
        output.push_str("    #[allow(non_upper_case_globals)]\n");
        output.push_str("    pub const ");
        output.push_str(&symbol.ident);
        output.push_str(": crate::symbol::Symbol = crate::symbol::Symbol::new(");
        output.push_str(&index.to_string());
        output.push_str(");\n");
    }
    output.push_str("}\n");

    fs::write(&out_path, output)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

#[derive(Debug)]
struct SymbolSpec {
    ident: String,
    string_literal: Option<String>,
}

fn parse_symbols(input: &str, path: &Path) -> Vec<SymbolSpec> {
    let mut symbols = Vec::new();
    for (line_no, line) in input.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with("//") {
            continue;
        }

        let (ident, string_literal) = match trimmed.split_once(':') {
            Some((left, right)) => {
                let ident = left.trim();
                let literal = right.trim();
                if ident.is_empty() || literal.is_empty() {
                    panic!("invalid symbol entry at {}:{}", path.display(), line_no + 1);
                }
                if !(literal.starts_with('"') && literal.ends_with('"')) {
                    panic!(
                        "expected string literal for symbol {} at {}:{}",
                        ident,
                        path.display(),
                        line_no + 1
                    );
                }
                (ident, Some(literal.to_string()))
            }
            None => (trimmed, None),
        };

        if !is_valid_ident(ident) {
            panic!("invalid symbol identifier '{}' at {}:{}", ident, path.display(), line_no + 1);
        }

        symbols.push(SymbolSpec {
            ident: ident.to_string(),
            string_literal,
        });
    }

    if symbols.is_empty() {
        panic!("no symbols found in {}", path.display());
    }

    symbols
}

fn is_valid_ident(ident: &str) -> bool {
    let mut chars = ident.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    if !(first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }

    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}
