// Copyright (C) 2019-2026 Provable Inc.
// This file is part of the Leo library.

// The Leo library is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// The Leo library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with the Leo library. If not, see <https://www.gnu.org/licenses/>.

//! Builds the symbol strings into `Symbol` values.

use std::{
    env,
    fmt::Write,
    fs,
    io::Read,
    path::{Path, PathBuf},
};

const PRE_DEFINED_HEADER: &str = "// @generated by build.rs. Do not edit.\nconst PRE_DEFINED: &[&str] = &[\n";
const PRE_DEFINED_FOOTER: &str = "];\n\n";
const PRE_DEFINED_IDENT_PREFIX: &str = "    \"";
const PRE_DEFINED_IDENT_SUFFIX: &str = "\",\n";
const PRE_DEFINED_LITERAL_PREFIX: &str = "    ";
const PRE_DEFINED_LITERAL_SUFFIX: &str = ",\n";

const SYM_HEADER: &str = "#[allow(non_upper_case_globals)]\npub mod sym {\n";
const SYM_FOOTER: &str = "}\n";
const SYM_CONST_PREFIX: &str = "    pub const ";
const SYM_CONST_MID: &str = ": crate::symbol::Symbol = crate::symbol::Symbol::new(";
const SYM_CONST_SUFFIX: &str = ");\n";

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing"));
    let input_path = manifest_dir.join("symbols.txt");
    println!("cargo:rerun-if-changed={}", input_path.display());

    let input = read_symbols(&input_path);
    let (symbol_count, pre_defined_len, sym_mod_len) = count_symbols(&input, &input_path);
    if symbol_count == 0 {
        panic!("no symbols found in {}", input_path.display());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let out_path = out_dir.join("symbols_generated.rs");

    let mut pre_defined = String::with_capacity(pre_defined_len);
    let mut sym_mod = String::with_capacity(sym_mod_len);
    pre_defined.push_str(PRE_DEFINED_HEADER);
    sym_mod.push_str(SYM_HEADER);

    let emitted = emit_symbols(&input, &input_path, &mut pre_defined, &mut sym_mod);
    debug_assert_eq!(emitted, symbol_count, "symbol counts changed between passes");

    pre_defined.push_str(PRE_DEFINED_FOOTER);
    sym_mod.push_str(SYM_FOOTER);

    let mut output = String::with_capacity(pre_defined.len() + sym_mod.len());
    output.push_str(&pre_defined);
    output.push_str(&sym_mod);

    fs::write(&out_path, output).unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn read_symbols(path: &Path) -> String {
    let input_len = fs::metadata(path).map(|meta| meta.len() as usize).unwrap_or(0);
    let mut input = String::with_capacity(input_len.saturating_add(1));
    let mut file = fs::File::open(path).unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    file.read_to_string(&mut input)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    input
}

fn is_valid_ident(ident: &str) -> bool {
    let mut chars = ident.chars();
    if let Some(first) = chars.next() {
        (first == '_' || first.is_ascii_alphabetic()) && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
    } else {
        false
    }
}

fn parse_symbol_line<'a>(line: &'a str, path: &Path, line_no: usize) -> Option<(&'a str, Option<&'a str>)> {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with("//") {
        return None;
    }

    let (ident, literal) = match trimmed.split_once(':') {
        Some((left, right)) => {
            let ident = left.trim();
            let literal = right.trim();
            if ident.is_empty() || literal.is_empty() {
                panic!("invalid symbol entry at {}:{}", path.display(), line_no);
            }
            if !(literal.starts_with('"') && literal.ends_with('"')) {
                panic!("expected string literal for symbol {} at {}:{}", ident, path.display(), line_no);
            }
            (ident, Some(literal))
        }
        None => (trimmed, None),
    };

    if !is_valid_ident(ident) {
        panic!("invalid symbol identifier '{}' at {}:{}", ident, path.display(), line_no);
    }

    Some((ident, literal))
}

fn count_symbols(input: &str, path: &Path) -> (usize, usize, usize) {
    let mut count = 0usize;
    let mut pre_defined_len = PRE_DEFINED_HEADER.len() + PRE_DEFINED_FOOTER.len();
    let mut sym_mod_len = SYM_HEADER.len() + SYM_FOOTER.len();

    for (line_no, line) in input.lines().enumerate() {
        let Some((ident, literal)) = parse_symbol_line(line, path, line_no + 1) else {
            continue;
        };

        let entry_len = match literal {
            Some(literal) => PRE_DEFINED_LITERAL_PREFIX.len() + literal.len() + PRE_DEFINED_LITERAL_SUFFIX.len(),
            None => PRE_DEFINED_IDENT_PREFIX.len() + ident.len() + PRE_DEFINED_IDENT_SUFFIX.len(),
        };
        pre_defined_len = pre_defined_len.saturating_add(entry_len);

        let index_len = decimal_len(count);
        let sym_len = SYM_CONST_PREFIX.len()
            + ident.len()
            + SYM_CONST_MID.len()
            + index_len
            + SYM_CONST_SUFFIX.len();
        sym_mod_len = sym_mod_len.saturating_add(sym_len);

        count += 1;
    }

    (count, pre_defined_len, sym_mod_len)
}

fn emit_symbols(input: &str, path: &Path, pre_defined: &mut String, sym_mod: &mut String) -> usize {
    let mut index = 0usize;
    for (line_no, line) in input.lines().enumerate() {
        let Some((ident, literal)) = parse_symbol_line(line, path, line_no + 1) else {
            continue;
        };

        match literal {
            Some(literal) => {
                pre_defined.push_str(PRE_DEFINED_LITERAL_PREFIX);
                pre_defined.push_str(literal);
                pre_defined.push_str(PRE_DEFINED_LITERAL_SUFFIX);
            }
            None => {
                pre_defined.push_str(PRE_DEFINED_IDENT_PREFIX);
                pre_defined.push_str(ident);
                pre_defined.push_str(PRE_DEFINED_IDENT_SUFFIX);
            }
        }

        sym_mod.push_str(SYM_CONST_PREFIX);
        sym_mod.push_str(ident);
        sym_mod.push_str(SYM_CONST_MID);
        // Writing to a String cannot fail.
        write!(sym_mod, "{index}").expect("writing symbol index failed");
        sym_mod.push_str(SYM_CONST_SUFFIX);
        index += 1;
    }

    index
}

fn decimal_len(mut value: usize) -> usize {
    let mut len = 1usize;
    while value >= 10 {
        value /= 10;
        len += 1;
    }
    len
}
